# Generated by Django 2.0.6 on 2018-06-23 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 14, 22, 58, 949568)),
        ),
    ]
