# Generated by Django 2.0.6 on 2018-06-23 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180623_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 6, 49, 43, 673655)),
        ),
    ]
