# Generated by Django 2.0.6 on 2018-06-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180623_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
