# Generated by Django 2.0.6 on 2018-06-23 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180623_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 7, 7, 51, 302178)),
        ),
    ]
