# Generated by Django 2.0.6 on 2018-06-23 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20180623_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 12, 23, 48, 858790)),
        ),
    ]
